# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Patrick Lafferty
email: patrick_lafferty@outlook.com
description: > # this means to ignore newlines until "baseurl:"
        allan please add description
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  patrick-lafferty

# Build settings
markdown: kramdown

gems:
    - jekyll-coffeescript
    - jekyll-paginate
    - github-pages

exclude: [vendor]

liquid:
        error_mode: strict

paginate: 10
paginate_path: "/blog/page:num/"
#permalink: /blog/:year/:month/:day/:title/

defaults:
        -
          scope:
                  path: ""
                  type: "posts"
          values:
                  permalink: /blog/:year/:month/:day/:title/

collections:
    projects:
        output: false

    menu_links:
        output: false
    
    games:
        output: false

    engines:
        output: false

    tools:
        output: false

    toolChains:
        output: false

